apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-chart.fullname" . }}-service
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
